# Site settings
title: Handshake Engineering
email: devs+blog@handshake.com
description: "We build software to connect great brands to local retailers and their customers [handshake.com](@handshake)."
baseurl: ""
url: "http://handshake.com"

# Build settings
markdown: kramdown
permalink: pretty
